package com.mycompany.myapp;

import com.codename1.io.Util;
import com.codename1.notifications.LocalNotification;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.TextField;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    static String ipaddress;
    public static String memberID;

    private Form current;
    public static Resources theme;
    private TextField field1;
    private TextField field2;
    public static NewPoject newPoject;
    public static String IP;
    public TextField textField;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        Util.register("ArrayList_EXTERNALISED",ArrayList_EXTERNALISED.class);
        newPoject = new NewPoject();

        Toolbar.setGlobalToolbar(true);

       
    }

    public void start() {
        if (current != null)
        {
            current.show();
            return;
        }
       
        //Home loginForm = new Home();
        // AdminDashboard adminDashboard = new AdminDashboard();
        //ProjectManagerLevel projectManagerLevel = new ProjectManagerLevel();
        TeamMemberLevel teamMemberLevel = new TeamMemberLevel();

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
